# Generated by Django 2.2.7 on 2019-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('connected', models.BooleanField(default=False)),
                ('food', models.ManyToManyField(blank=True, related_name='user', to='comparator.Food')),
            ],
        ),
    ]
