# Generated by Django 2.2.7 on 2019-12-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('code', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugars', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pict', models.URLField()),
                ('off_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator.Category')),
            ],
        ),
    ]
