# Generated by Django 2.2.7 on 2019-12-13 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
    ]
